FROM rust:1.52 AS builder
WORKDIR /app

# To cache the build dependencies (which take a loooooong time to compile),
# we setup a new dummy project and copy over only the Cargo files
RUN cargo init --bin
COPY Cargo.toml Cargo.lock ./
RUN cargo build --tests

# Copy the actual source of the project and compile the tests.
# Be sure to `touch` the entrypoint so that cargo thinks they are dirty.
COPY . .
RUN touch src/main.rs && \
    cargo test --no-run

# When the image is executed, run the tests
ENTRYPOINT cargo test
